name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: python3 --version

  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: python3 hello.py

  deploy-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "Finalizado"
